use super::Helper;

pub(super) fn helper_name(helper: Helper) -> &'static str {
    match helper {
        Helper::LoadI32 => "load_i32",
        Helper::Load8U => "load8_u",
        Helper::Load8S => "load8_s",
        Helper::Load16U => "load16_u",
        Helper::Load16S => "load16_s",
        Helper::LoadI64 => "load_i64",
        Helper::LoadF32 => "load_f32",
        Helper::LoadF64 => "load_f64",
        Helper::Load8UI64 => "load8_u_i64",
        Helper::Load8SI64 => "load8_s_i64",
        Helper::Load16UI64 => "load16_u_i64",
        Helper::Load16SI64 => "load16_s_i64",
        Helper::Load32UI64 => "load32_u_i64",
        Helper::Load32SI64 => "load32_s_i64",
        Helper::StoreI32 => "store_i32",
        Helper::Store8 => "store8",
        Helper::Store16 => "store16",
        Helper::StoreI64 => "store_i64",
        Helper::StoreF32 => "store_f32",
        Helper::StoreF64 => "store_f64",
        Helper::Store8I64 => "store8_i64",
        Helper::Store16I64 => "store16_i64",
        Helper::Store32I64 => "store32_i64",
        Helper::LoadV128 => "load_v128",
        Helper::StoreV128 => "store_v128",
        Helper::Load8Splat => "load8_splat",
        Helper::Load16Splat => "load16_splat",
        Helper::Load32Splat => "load32_splat",
        Helper::Load64Splat => "load64_splat",
        Helper::Load32Zero => "load32_zero",
        Helper::Load64Zero => "load64_zero",
        Helper::Load8Lane => "load8_lane",
        Helper::Load16Lane => "load16_lane",
        Helper::Load32Lane => "load32_lane",
        Helper::Load64Lane => "load64_lane",
        Helper::Store8Lane => "store8_lane",
        Helper::Store16Lane => "store16_lane",
        Helper::Store32Lane => "store32_lane",
        Helper::Store64Lane => "store64_lane",
        Helper::Grow => "memory_grow",
        Helper::MemoryFill => "memory_fill",
        Helper::MemoryCopy => "memory_copy",
        Helper::TableCopy => "table_copy",
        Helper::TableFill => "table_fill",
    }
}

/// All memory helpers, in a deterministic emission order.
pub(super) const HELPER_ORDER: [Helper; 44] = [
    Helper::LoadI32,
    Helper::Load8U,
    Helper::Load8S,
    Helper::Load16U,
    Helper::Load16S,
    Helper::LoadI64,
    Helper::LoadF32,
    Helper::LoadF64,
    Helper::Load8UI64,
    Helper::Load8SI64,
    Helper::Load16UI64,
    Helper::Load16SI64,
    Helper::Load32UI64,
    Helper::Load32SI64,
    Helper::StoreI32,
    Helper::Store8,
    Helper::Store16,
    Helper::StoreI64,
    Helper::StoreF32,
    Helper::StoreF64,
    Helper::Store8I64,
    Helper::Store16I64,
    Helper::Store32I64,
    Helper::LoadV128,
    Helper::StoreV128,
    Helper::Load8Splat,
    Helper::Load16Splat,
    Helper::Load32Splat,
    Helper::Load64Splat,
    Helper::Load32Zero,
    Helper::Load64Zero,
    Helper::Load8Lane,
    Helper::Load16Lane,
    Helper::Load32Lane,
    Helper::Load64Lane,
    Helper::Store8Lane,
    Helper::Store16Lane,
    Helper::Store32Lane,
    Helper::Store64Lane,
    Helper::Grow,
    Helper::MemoryFill,
    Helper::MemoryCopy,
    Helper::TableCopy,
    Helper::TableFill,
];

/// The source lines of one memory helper method (bounds-checked via indexing,
/// so an out-of-range access panics — mirroring a wasm trap).
pub(super) fn helper_lines(helper: Helper) -> Vec<String> {
    let owned = |lines: &[&str]| lines.iter().map(|s| (*s).to_string()).collect::<Vec<_>>();
    match helper {
        Helper::LoadI32 => owned(&[
            "fn load_i32(&self, addr: u32, offset: u32) -> i32 {",
            "    let a = addr as usize + offset as usize;",
            "    i32::from_le_bytes([self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3]])",
            "}",
        ]),
        Helper::Load8U => owned(&[
            "fn load8_u(&self, addr: u32, offset: u32) -> i32 {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem()[a] as i32",
            "}",
        ]),
        Helper::Load8S => owned(&[
            "fn load8_s(&self, addr: u32, offset: u32) -> i32 {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem()[a] as i8 as i32",
            "}",
        ]),
        Helper::Load16U => owned(&[
            "fn load16_u(&self, addr: u32, offset: u32) -> i32 {",
            "    let a = addr as usize + offset as usize;",
            "    u16::from_le_bytes([self.mem()[a], self.mem()[a + 1]]) as i32",
            "}",
        ]),
        Helper::Load16S => owned(&[
            "fn load16_s(&self, addr: u32, offset: u32) -> i32 {",
            "    let a = addr as usize + offset as usize;",
            "    i16::from_le_bytes([self.mem()[a], self.mem()[a + 1]]) as i32",
            "}",
        ]),
        Helper::StoreI32 => owned(&[
            "fn store_i32(&mut self, addr: u32, offset: u32, value: i32) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 4].copy_from_slice(&value.to_le_bytes());",
            "}",
        ]),
        Helper::Store8 => owned(&[
            "fn store8(&mut self, addr: u32, offset: u32, value: i32) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a] = value as u8;",
            "}",
        ]),
        Helper::Store16 => owned(&[
            "fn store16(&mut self, addr: u32, offset: u32, value: i32) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 2].copy_from_slice(&(value as u16).to_le_bytes());",
            "}",
        ]),
        Helper::LoadI64 => owned(&[
            "fn load_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    i64::from_le_bytes([self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3], self.mem()[a + 4], self.mem()[a + 5], self.mem()[a + 6], self.mem()[a + 7]])",
            "}",
        ]),
        Helper::LoadF32 => owned(&[
            "fn load_f32(&self, addr: u32, offset: u32) -> f32 {",
            "    let a = addr as usize + offset as usize;",
            "    f32::from_le_bytes([self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3]])",
            "}",
        ]),
        Helper::LoadF64 => owned(&[
            "fn load_f64(&self, addr: u32, offset: u32) -> f64 {",
            "    let a = addr as usize + offset as usize;",
            "    f64::from_le_bytes([self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3], self.mem()[a + 4], self.mem()[a + 5], self.mem()[a + 6], self.mem()[a + 7]])",
            "}",
        ]),
        Helper::Load8UI64 => owned(&[
            "fn load8_u_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem()[a] as i64",
            "}",
        ]),
        Helper::Load8SI64 => owned(&[
            "fn load8_s_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem()[a] as i8 as i64",
            "}",
        ]),
        Helper::Load16UI64 => owned(&[
            "fn load16_u_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    u16::from_le_bytes([self.mem()[a], self.mem()[a + 1]]) as i64",
            "}",
        ]),
        Helper::Load16SI64 => owned(&[
            "fn load16_s_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    i16::from_le_bytes([self.mem()[a], self.mem()[a + 1]]) as i64",
            "}",
        ]),
        Helper::Load32UI64 => owned(&[
            "fn load32_u_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    u32::from_le_bytes([self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3]]) as i64",
            "}",
        ]),
        Helper::Load32SI64 => owned(&[
            "fn load32_s_i64(&self, addr: u32, offset: u32) -> i64 {",
            "    let a = addr as usize + offset as usize;",
            "    i32::from_le_bytes([self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3]]) as i64",
            "}",
        ]),
        Helper::StoreI64 => owned(&[
            "fn store_i64(&mut self, addr: u32, offset: u32, value: i64) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 8].copy_from_slice(&value.to_le_bytes());",
            "}",
        ]),
        Helper::StoreF32 => owned(&[
            "fn store_f32(&mut self, addr: u32, offset: u32, value: f32) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 4].copy_from_slice(&value.to_le_bytes());",
            "}",
        ]),
        Helper::StoreF64 => owned(&[
            "fn store_f64(&mut self, addr: u32, offset: u32, value: f64) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 8].copy_from_slice(&value.to_le_bytes());",
            "}",
        ]),
        Helper::Store8I64 => owned(&[
            "fn store8_i64(&mut self, addr: u32, offset: u32, value: i64) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a] = value as u8;",
            "}",
        ]),
        Helper::Store16I64 => owned(&[
            "fn store16_i64(&mut self, addr: u32, offset: u32, value: i64) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 2].copy_from_slice(&(value as u16).to_le_bytes());",
            "}",
        ]),
        Helper::Store32I64 => owned(&[
            "fn store32_i64(&mut self, addr: u32, offset: u32, value: i64) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 4].copy_from_slice(&(value as u32).to_le_bytes());",
            "}",
        ]),
        // A v128 load/store moves 16 bytes to/from memory as a little-endian
        // `u128`; the slice access is bounds-checked, so an out-of-range access
        // panics (a wasm trap).
        Helper::LoadV128 => owned(&[
            "fn load_v128(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let mut b = [0u8; 16];",
            "    b.copy_from_slice(&self.mem()[a..a + 16]);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::StoreV128 => owned(&[
            "fn store_v128(&mut self, addr: u32, offset: u32, value: u128) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a..a + 16].copy_from_slice(&value.to_le_bytes());",
            "}",
        ]),
        // `load*_splat` reads one element and broadcasts it to every lane;
        // `load*_zero` reads one into the low lane and zeroes the rest. Each
        // access is bounds-checked, so an out-of-range read traps.
        Helper::Load8Splat => owned(&[
            "fn load8_splat(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    u128::from_le_bytes([self.mem()[a]; 16])",
            "}",
        ]),
        Helper::Load16Splat => owned(&[
            "fn load16_splat(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let lane = [self.mem()[a], self.mem()[a + 1]];",
            "    let mut b = [0u8; 16];",
            "    let mut i = 0;",
            "    while i < 16 {",
            "        b[i..i + 2].copy_from_slice(&lane);",
            "        i += 2;",
            "    }",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load32Splat => owned(&[
            "fn load32_splat(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let lane = [self.mem()[a], self.mem()[a + 1], self.mem()[a + 2], self.mem()[a + 3]];",
            "    let mut b = [0u8; 16];",
            "    let mut i = 0;",
            "    while i < 16 {",
            "        b[i..i + 4].copy_from_slice(&lane);",
            "        i += 4;",
            "    }",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load64Splat => owned(&[
            "fn load64_splat(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let mut b = [0u8; 16];",
            "    b[0..8].copy_from_slice(&self.mem()[a..a + 8]);",
            "    b.copy_within(0..8, 8);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load32Zero => owned(&[
            "fn load32_zero(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let mut b = [0u8; 16];",
            "    b[0..4].copy_from_slice(&self.mem()[a..a + 4]);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load64Zero => owned(&[
            "fn load64_zero(&self, addr: u32, offset: u32) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let mut b = [0u8; 16];",
            "    b[0..8].copy_from_slice(&self.mem()[a..a + 8]);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        // `load*_lane` replaces one lane of `value` with an element read from
        // memory; `store*_lane` writes one lane of `value` back to memory. `lane`
        // is a validated lane index, so the byte range is always in bounds.
        Helper::Load8Lane => owned(&[
            "fn load8_lane(&self, addr: u32, offset: u32, value: u128, lane: usize) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let mut b = value.to_le_bytes();",
            "    b[lane] = self.mem()[a];",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load16Lane => owned(&[
            "fn load16_lane(&self, addr: u32, offset: u32, value: u128, lane: usize) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let o = lane * 2;",
            "    let mut b = value.to_le_bytes();",
            "    b[o..o + 2].copy_from_slice(&self.mem()[a..a + 2]);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load32Lane => owned(&[
            "fn load32_lane(&self, addr: u32, offset: u32, value: u128, lane: usize) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let o = lane * 4;",
            "    let mut b = value.to_le_bytes();",
            "    b[o..o + 4].copy_from_slice(&self.mem()[a..a + 4]);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Load64Lane => owned(&[
            "fn load64_lane(&self, addr: u32, offset: u32, value: u128, lane: usize) -> u128 {",
            "    let a = addr as usize + offset as usize;",
            "    let o = lane * 8;",
            "    let mut b = value.to_le_bytes();",
            "    b[o..o + 8].copy_from_slice(&self.mem()[a..a + 8]);",
            "    u128::from_le_bytes(b)",
            "}",
        ]),
        Helper::Store8Lane => owned(&[
            "fn store8_lane(&mut self, addr: u32, offset: u32, value: u128, lane: usize) {",
            "    let a = addr as usize + offset as usize;",
            "    self.mem_mut()[a] = value.to_le_bytes()[lane];",
            "}",
        ]),
        Helper::Store16Lane => owned(&[
            "fn store16_lane(&mut self, addr: u32, offset: u32, value: u128, lane: usize) {",
            "    let a = addr as usize + offset as usize;",
            "    let o = lane * 2;",
            "    self.mem_mut()[a..a + 2].copy_from_slice(&value.to_le_bytes()[o..o + 2]);",
            "}",
        ]),
        Helper::Store32Lane => owned(&[
            "fn store32_lane(&mut self, addr: u32, offset: u32, value: u128, lane: usize) {",
            "    let a = addr as usize + offset as usize;",
            "    let o = lane * 4;",
            "    self.mem_mut()[a..a + 4].copy_from_slice(&value.to_le_bytes()[o..o + 4]);",
            "}",
        ]),
        Helper::Store64Lane => owned(&[
            "fn store64_lane(&mut self, addr: u32, offset: u32, value: u128, lane: usize) {",
            "    let a = addr as usize + offset as usize;",
            "    let o = lane * 8;",
            "    self.mem_mut()[a..a + 8].copy_from_slice(&value.to_le_bytes()[o..o + 8]);",
            "}",
        ]),
        // `delta` is an unsigned page count. Growth past the wasm32 limit of
        // 65536 pages (4 GiB) fails, returning -1 as the wasm spec requires;
        // the declared maximum is not tracked, so only that hard cap applies.
        Helper::Grow => owned(&[
            "fn memory_grow(&mut self, delta: i32) -> i32 {",
            "    let old_pages = (self.mem().len() / 65536) as u64;",
            "    let new_pages = old_pages + (delta as u32 as u64);",
            "    if new_pages > 65536 {",
            "        return -1;",
            "    }",
            "    self.mem_mut().resize((new_pages as usize) * 65536, 0);",
            "    old_pages as i32",
            "}",
        ]),
        // Bulk operations. An out-of-bounds range panics on the slice access or
        // `copy_within` (a wasm trap); `copy_within` is memmove, so overlapping
        // source and destination copy correctly.
        Helper::MemoryFill => owned(&[
            "fn memory_fill(&mut self, dest: u32, val: i32, len: u32) {",
            "    let d = dest as usize;",
            "    self.mem_mut()[d..d + len as usize].fill(val as u8);",
            "}",
        ]),
        Helper::MemoryCopy => owned(&[
            "fn memory_copy(&mut self, dest: u32, src: u32, len: u32) {",
            "    let s = src as usize;",
            "    let d = dest as usize;",
            "    self.mem_mut().copy_within(s..s + len as usize, d);",
            "}",
        ]),
        Helper::TableCopy => owned(&[
            "fn table_copy(&mut self, dest: u32, src: u32, len: u32) {",
            "    let s = src as usize;",
            "    let d = dest as usize;",
            "    self.table_mut().copy_within(s..s + len as usize, d);",
            "}",
        ]),
        Helper::TableFill => owned(&[
            "fn table_fill(&mut self, dest: u32, val: u32, len: u32) {",
            "    let d = dest as usize;",
            "    self.table_mut()[d..d + len as usize].fill(val);",
            "}",
        ]),
    }
}
